Iter9
Nchezhegova/metrics-alerts pull request #6
Opened 2024-01-08 11:09 UTC by Nchezhegova

2024-01-10 08:00 UTC, tmvrus requested changes

2024-01-12 12:55 UTC, Nchezhegova commented on cmd/agent/main.go
> +	req, err := http.NewRequest("POST", url, &compressBody)
Если убрать, то выводится ошибка:

Cannot use 'compressBody' (type bytes.Buffer) as the type io.Reader Type does not implement 'io.Reader' as the 'Read' method has a pointer receiver

2024-01-13 11:28 UTC, tmvrus commented on cmd/agent/main.go
> +	req, err := http.NewRequest("POST", url, &compressBody)
да, все верно
я подумал что compressBody это уже io.Reader, этого можно добавиться заранее объявив тип
var compressBody io.Reader

2024-01-13 12:35 UTC, tmvrus approved these changes
все еще fmt для логирования, дурной тон

2024-01-13 14:25 UTC, merged